[build]
builder = "nixpacks"

[build.env]
BP_PHP_VERSION = "8.2"
BP_PHP_WEB_DIR = "public"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
sleepApplication = false

# Health check optionnel
healthcheckPath = "/api/v1/zones"
healthcheckTimeout = 300
